version: "3"

services:

    shopware:
      # use either tag "latest" or any other version like "6.1.5", ...
      image: dockware/dev:latest

      container_name: slox_test_1
      ports:
         - "22:22"     # ssh
         - "80:80"     # apache2
         - "443:443"   # apache2 https
         - "8888:8888" # watch admin
         - "9998:9998" # watch storefront proxy
         - "9999:9999" # watch storefront
         - "3306:3306" # mysql port
      volumes:
         - ./slox_example_plugin:/var/www/html/custom/plugins/slox_example_plugin
         - ./pimpMyLog/logLinker.json:/var/www/pimpmylog/config.user.d/logLinker.json

         
      networks:
         - web
      environment:
         - XDEBUG_ENABLED=1
         - DISABLE_ADMIN_COMPILATION_TYPECHECK=1
         - SHOPWARE_ADMIN_BUILD_ONLY_EXTENSIONS=1
         - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
         - APP_ENV=dev
         - NODE_OPTIONS=--openssl-legacy-provider

networks:
  web:
    external: false
